### ISSUE TITLE
La barra de "detalle sube", de la sección detalle se muestra incorrecta en FireFox y Explorer Edge

### ISSUE THREAD

**Issue by jordivs** [RepositorioNacionalCultura/Front#10]
En la sección de detalle de las obras la barra de Detalle sube se muestra diferente en los navegadores. Se probo en los siguientes Browsers

FireFox 57.0.4 (64-bit) 11.192.16299.0

![4](https://user-images.githubusercontent.com/7914633/35056294-04d04714-fb77-11e7-94e1-2b4973f878a7.PNG)

Explorer Edge
![2](https://user-images.githubusercontent.com/7914633/35019388-47b91302-faec-11e7-88a6-1f580611a62f.PNG)

Google Chrome Versión 63.0.3239.132 (Build oficial) (64 bits)
![3](https://user-images.githubusercontent.com/7914633/35056196-c2f0514a-fb76-11e7-99ad-7fbffbb44006.PNG)

Internet Explorer 11.192.16299.0
![5](https://user-images.githubusercontent.com/7914633/35056407-58e755e0-fb77-11e7-8c3a-b5ea1359e763.PNG)

Resultado:
En FireFox y en Explorer Edge se muestran incorrectamente

**Comment by RogelioEsperon** [comment]
En mi máquina virtual ya se ve bien. ¿@jordivs puedes checar si ya se corrigió?

**Comment by jordivs** [comment]
@RogelioEsperon  ¿Dónde subiste el cambio?

**Comment by RogelioEsperon** [comment]
En http://129.144.24.140:8080/swb/cultura/

**Comment by haxdai** [comment]
La nueva versión del diseño ya está en progreso, por lo que el issue quedará invalidado.
