### ISSUE TITLE
Display del buscador tapa el imput para realizar una busqueda

### ISSUE THREAD

**Issue by jordivs** [RepositorioNacionalCultura/Front#12]
En el browswe  FireFox  el Display de sugerencias tapa el imput de la busquda, lo que impide ver que se esta escribiendo.
**Browser probados:**
** FireFox 57.0.4 (64-bit)**
![ff](https://user-images.githubusercontent.com/7914633/35110061-90f24028-fc3d-11e7-95d3-a9154c02fb3d.PNG)

**GooleChrome Versión 63.0.3239.132 (Build oficial) (64 bits)** 
Se ve correctamente 
![gc](https://user-images.githubusercontent.com/7914633/35111523-1767e7b8-fc41-11e7-86c0-3acbd8b45ddd.PNG)

**Internet Explorer 11.192.16299.0**  Se muestra ala derecha
![ie](https://user-images.githubusercontent.com/7914633/35112011-5a242d90-fc42-11e7-9fa5-b5e55105bebb.PNG)

**Microsoft Edge** Se muestra encima del imput de busqueda 
![me](https://user-images.githubusercontent.com/7914633/35114746-7002c9f6-fc4b-11e7-8182-49a184fb08b0.PNG)

**Ambiente**

S.O. Centos.
A.S: Tomcat 8.5.14 
DB: Hipersonic
JDK: 8

**Comment by RogelioEsperon** [comment]
Ya quedó. El único que no puedo comprobar es la vista en Explorer 11, mi máquiina virtual no lo muestra.

**Comment by haxdai** [comment]
Con el nuevo diseño, el issue quedará invalidado
