### ISSUE TITLE
Feature: Usuario autenticado, no muestra el nombre

### ISSUE THREAD

**Issue by jordivs** [RepositorioNacionalCultura/Front#60]
No se muestra el usuario con el cual se autentica 

Pasos para replicar el issue:

1.- Autenticarse al sitio del repositorio
2.- En el menú del usuario seleccionar "Mis Colecciones"
Resultado:
El nombre que se visualiza no es el del usuario autenticado
![imagen](https://user-images.githubusercontent.com/7914633/41879946-702226a2-78a1-11e8-987e-873bc4e460cc.png)

**Comment by JRedentor** [comment]
@jordivs, creo que sería bueno preguntarle a @sercht si él desarrolló este recurso, porque no es mío.

**Comment by sercht** [comment]
Corregido
![trace](https://user-images.githubusercontent.com/25464697/42011814-de5333e0-7a5a-11e8-9438-de49f23a80ea.jpg)

**Comment by jordivs** [comment]
Listo!!
